### PR TITLE
refactoring - do not merge (yet)

### PR DESCRIPTION
**Pull request by kristianmandrup**
Working on a major refactor to make it more extensible and configurable.

Do not merge this yet. 

I'd love some insights on the current state of the library, since it seems like a mix of old and new and compiled (published) code.
Cheers.

### CODE REVIEW

**Comment by franciscop** [comment]
Hey thanks!

As you can see this project is not really finished nor maintained. I am not using it anywhere, since for some [smaller project of mine](https://core.cards/) where it might be useful I'm just using [indexeddb with `brownies`](https://github.com/franciscop/brownies) and its `subscribe()` method. 

The project `brownies` uses `Proxy` very similar to `atama` since I applied what I learned here. But they are very different tech and so `atama` is currently unused, unfinished and unmaintained.

You have a couple of options:
- Fork this project, clean it up, continue dev and publish it. I would recommend you to find a better name but that's up to you :)
- Become the maintainer of `atama`. I am not going to do anything with this library, so you might as well continue with it. I'd transfer full rights and repos.

**Comment by franciscop** [comment]
Tech-wise, I try to avoid factories or interchangeable engines because in my experience they very rarely work out *for smaller libraries*, especially considering the aditional complexity it brings.

By keeping my libraries small, fork+replace engine+publish project is normally much better if you want a similar interface with a totally different engine.

See https://blog.codinghorror.com/rule-of-three/

**Comment by kristianmandrup** [comment]
All sounds good to me. I understand your reasonings. For me, factories have worked fine in the past in other libs I have created or forked. I often feel "stuck" in what library authors have pre-decided. 
I don't mind a little extra complexity trade-off for the extra flexibility. All comes down to taste and pref.

The reason I introduced the factories in the first place was for a use case, where I needed to treat an array as "a whole". I'll be glad to take over ownership for now and see what I can do. 

Thank you also for pointing me in other directions for proxy state management. Atama was the first obvious hit when I looked for a library to provide a solution. Cheers!

**Comment by franciscop** [comment]
Agreed, same feeling. That is why I made Atama, I felt stuck with Redux 😉

Oh `brownies` is another library of mine, it's not proxy management but instead can be considered state management through browser Storage tech, just pointing out that it's why I don't use Atama anymore.

Sure, to make sure I understood properly, do you want me to transfer the `atama` repo and npm package? (It's fine)

**Comment by kristianmandrup** [comment]
I will have a look at brownies then and include a Resources section with links to these alternatives.

Hmm, I think I will just roll my own lib using your core as the base to go from. Will keep you posted ;)

**Pull request closed without merging**
